### ISSUE TITLE
Programatically add PYTHONPATH=. as one of the first thing in the code

### ISSUE THREAD

**Issue by dameyerdave** [bdragon300/mongoengine-migrate#21]
Because mongoengine_migrate makemigrations is used in the scope of the current project (directory) it would make sense to add the current directory (`.`) to the PYTHONPATH. Otherwise I always get the error
```
mongoengine_migrate makemigrations -m models.data
...
ModuleNotFoundError: No module named 'models'
```
As a workaround I call it like this
```
PYTHONPATH=. mongoengine_migrate makemigrations -m models.data
```

**Comment by bdragon300** [comment]
Fixed in dev branch
