### ISSUE TITLE
Fix email regex in `to_email_string` converter

### ISSUE THREAD

**Issue by bdragon300** [bdragon300/mongoengine-migrate#24]
Now the format of email string does not check. It's needed to fix regex.

**Comment by vmdhhh** [comment]
@bdragon300  Can you please describe the issue a bit?
I would like to help if i can and if its ok.

**Comment by bdragon300** [comment]
Hi @vmdhhh . This issue is about to add email format check in `to_email_string` converter. It located in `mongoengine_migrate.fields.converters.common`. It's needed to add regex which checks if string field value in documents of given collection has email format. Now only `.*` regex there, i.e. no check. Pay attention that this regex will be executed by MongoDB query, not in python.

`to_email_string` invokes when field converts to `EmailField` from string or dynamic field.

**Comment by vmdhhh** [comment]
@bdragon300 Please take a look at the #34 and let me know.

**Comment by vmdhhh** [comment]
@bdragon300 I also might have figured out the resolution for #33 .
Do you want me to add the change in this PR ?

**Comment by bdragon300** [comment]
@vmdhhh I think it should be a separate PR

**Comment by bdragon300** [comment]
Fixed
