### ISSUE TITLE
`parameters` arg in `Schema.Document` constructor also adds `parameters` key to schema

### ISSUE THREAD

**Issue by bdragon300** [bdragon300/mongoengine-migrate#33]
Now `parameters` arg in `Schema.Document` constructor also adds schema key with given value along with `.parameters` attribute:

```
>>> print(Schema.Document(a=1, b=2, parameters={5: 6}))
Document({'a': 1, 'b': 2, 'parameters': {5: 6}}, parameters={5: 6})
```

Should be:

```
>>> print(Schema.Document(a=1, b=2, parameters={5: 6}))
Document({'a': 1, 'b': 2}, parameters={5: 6})
```

**Comment by vmdhhh** [comment]
@bdragon300 I tried fixing this in #36. 
The only thing is if the user also wants to use `parameters` as key, then it should be given in `{key: value}` format.
Otherwise, it will raise a `SyntaxError: keyword argument repeated`.
Please have a look.

**Comment by bdragon300** [comment]
@vmdhhh Yes, I've inserted lines smth like `del ...['parameters']` to unit tests as temp workaround for this problem. Now they may be removed then, most of errors in build are tied up with this.

**Comment by bdragon300** [comment]
@vmdhhh parameters should be passed as keyword arg, other Schema.Document contents may be passed as dict or keyword args. It's behavior should be similar to built-in dict, except for `parameters` arg. For example:

```
Schema.Document(a=1, b=2, parameters={5: 6})
Document({'a': 1, 'b': 2}, parameters={5: 6})
```

or

```
Schema.Document({'a': 1, 'b': 2}, parameters={5: 6})
Document({'a': 1, 'b': 2}, parameters={5: 6})   #The same
```

**Comment by vmdhhh** [comment]
> 
> 
> @vmdhhh Yes, I've inserted lines smth like `del ...['parameters']` to unit tests as temp workaround for this problem. Now they may be removed then, most of errors in build are tied up with this.

I removed the "deletes". Seems that was only the problem.
